name: build
on:
  push:
    branches: ['ocr_config']

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  container-job:
    runs-on: ghcr.io/banned-historical-archives/ocr:main
    steps:
      - uses: actions/checkout@v4
        - with:
          path: './main'
          ref: 'main'
      - uses: actions/checkout@v4
        - with:
          path: './ocr_config'
          ref: 'ocr_config'
      - uses: actions/checkout@v4
        - with:
          path: './ocr_cache'
          ref: 'ocr_cache'
      - name: Use Node.js
        uses: actions/setup-node@v3
        working-directory: ./ocr_config
      - run: npm install
      - run: node --version